using System.Globalization;
using System.Text;
using CsvHelper;
using CsvHelper.Configuration;

namespace Wms.Core.WebApi.Services;

/// <summary>
/// 导出格式
/// </summary>
public enum ExportFormat
{
    Excel,
    Csv,
    Pdf
}

/// <summary>
/// 导出服务接口
/// </summary>
public interface IExportService
{
    Task<byte[]> ExportAsync<T>(IEnumerable<T> data, ExportFormat format, string fileName = "export");
}

/// <summary>
/// 导出服务实现
/// </summary>
public class ExportService : IExportService
{
    private readonly ILogger<ExportService> _logger;

    public ExportService(
        ILogger<ExportService> logger)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    public async Task<byte[]> ExportAsync<T>(IEnumerable<T> data, ExportFormat format, string fileName = "export")
    {
        var dataList = data.ToList();

        _logger.LogInformation("开始导出数据: 格式={Format}, 记录数={Count}", format, dataList.Count);

        return format switch
        {
            ExportFormat.Excel => await ExportToExcelAsync(dataList),
            ExportFormat.Csv => await ExportToCsvAsync(dataList),
            ExportFormat.Pdf => await ExportToPdfAsync(dataList, fileName),
            _ => throw new ArgumentException($"不支持的导出格式: {format}")
        };
    }

    private async Task<byte[]> ExportToExcelAsync<T>(List<T> data)
    {
        // 使用 CSVHelper 创建 Excel 兼容格式（TSV - Tab Separated Values）
        await using var memoryStream = new MemoryStream();
        await using var streamWriter = new StreamWriter(memoryStream, Encoding.UTF8);
        await using var csvWriter = new CsvWriter(streamWriter, new CsvConfiguration(CultureInfo.InvariantCulture)
        {
            HasHeaderRecord = true,
            Delimiter = "\t" // Tab 分隔，Excel 可以直接打开
        });

        await csvWriter.WriteRecordsAsync(data);
        await csvWriter.FlushAsync();

        return memoryStream.ToArray();
    }

    private async Task<byte[]> ExportToCsvAsync<T>(List<T> data)
    {
        await using var memoryStream = new MemoryStream();
        await using var streamWriter = new StreamWriter(memoryStream, Encoding.UTF8);
        await using var csvWriter = new CsvWriter(streamWriter, new CsvConfiguration(CultureInfo.InvariantCulture)
        {
            HasHeaderRecord = true,
            Delimiter = ",",
            Encoding = Encoding.UTF8
        });

        await csvWriter.WriteRecordsAsync(data);
        await csvWriter.FlushAsync();

        return memoryStream.ToArray();
    }

    private Task<byte[]> ExportToPdfAsync<T>(List<T> data, string fileName)
    {
        // 简单的 PDF 生成（实际生产环境建议使用 iTextSharp 或 PdfSharp）
        // 这里我们返回一个包含数据的简单文本格式的"伪PDF"
        // 对于真正的 PDF 支持，应该添加 PdfSharp 或 iTextSharp 包

        var sb = new StringBuilder();
        sb.AppendLine("%PDF-1.4");
        sb.AppendLine($"% Title: {fileName}");
        sb.AppendLine("% Generated by WMS Core API");
        sb.AppendLine();

        if (data.Any())
        {
            var first = data[0];
            var properties = first!.GetType().GetProperties();

            // 写入表头
            var headers = string.Join(" | ", properties.Select(p => p.Name));
            sb.AppendLine(new string('-', headers.Length));
            sb.AppendLine(headers);
            sb.AppendLine(new string('-', headers.Length));

            // 写入数据
            foreach (var item in data)
            {
                var values = string.Join(" | ", properties.Select(p =>
                    p.GetValue(item)?.ToString() ?? string.Empty));
                sb.AppendLine(values);
            }

            sb.AppendLine(new string('-', headers.Length));
            sb.AppendLine($"Total Records: {data.Count}");
        }
        else
        {
            sb.AppendLine("No data available");
        }

        // 注意：这不是一个真正的 PDF 文件！
        // 实际项目中应该使用 PdfSharp 或 iTextSharp 来生成真正的 PDF
        _logger.LogWarning("PDF export using placeholder implementation. Consider using PdfSharp or iTextSharp for production.");

        return Task.FromResult(Encoding.UTF8.GetBytes(sb.ToString()));
    }
}

/// <summary>
/// 导出服务扩展方法
/// </summary>
public static class ExportServiceExtensions
{
    public static async Task<byte[]> ExportToExcelAsync<T>(this IEnumerable<T> data)
    {
        // 使用 CsvHelper 创建简单的 Excel 兼容格式
        await using var memoryStream = new MemoryStream();
        await using var streamWriter = new StreamWriter(memoryStream, Encoding.UTF8);
        await using var csvWriter = new CsvWriter(streamWriter, new CsvConfiguration(CultureInfo.InvariantCulture)
        {
            HasHeaderRecord = true,
            Delimiter = "\t" // Tab 分隔，Excel 可以直接打开
        });

        await csvWriter.WriteRecordsAsync(data);
        await csvWriter.FlushAsync();

        return memoryStream.ToArray();
    }
}
